### ISSUE TITLE
The camera-streamer compiled based on libcamera0.2 cannot run normally

### ISSUE THREAD

**Issue by tom-ard** [ayufan/camera-streamer#139]
When I updated libcamera to version 0.2, the following error occurred when compiling and running camera-streamer again.
![image](https://github.com/ayufan/camera-streamer/assets/100827463/015c7e56-b524-4b16-a456-37d66c832e08)
![image](https://github.com/ayufan/camera-streamer/assets/100827463/4b1f099b-5fc7-4345-8a91-b1cb3867b079)

By printing some key information, I found that this was caused by the RAW stream's configuration.stride equal to 4128.
![image](https://github.com/ayufan/camera-streamer/assets/100827463/f8e6de64-a087-4835-8bea-f78e628d4fd5)

You only need to force configuration.stride to be 0 to solve this problem.
![image](https://github.com/ayufan/camera-streamer/assets/100827463/ccae72e9-6a9f-46ba-887b-ff0d765209da)
![image](https://github.com/ayufan/camera-streamer/assets/100827463/ac622271-a11d-49f5-9b27-f9506ed102a9)

**Comment by CmdrAdama** [comment]
I can confirm that making this change manually and rebuilding it resolved the issue for me as well.

**Comment by DropbearNinja** [comment]
Where do you set configuration.stride = 0?
