### ISSUE TITLE
Logitech c920 not working with camera-streamer 

### ISSUE THREAD

**Issue by fabiandj64** [ayufan/camera-streamer#148]
I tried almost everything I could find online to get it to work but with no success.
Adding log and conf

[crowsnest.log](https://github.com/ayufan/camera-streamer/files/15210960/crowsnest.log)
[crowsnest.conf](https://github.com/ayufan/camera-streamer/files/15210961/crowsnest.txt)

**Comment by fabiandj64** [comment]
All always get an "Can't set format" error

**Comment by fabiandj64** [comment]
i changed a few entries in the camer-streamer.service file and now it is working.

**Comment by elgatobavaria** [comment]
@fabiandj64 Would be nice if you could share your changes with the community. I would like to use the camera, too. Thank you

**Comment by fabiandj64** [comment]
i dont even know if the changes to the camera-streamer.service made a difference; i tried to look up the service and saw, that they changed to having different services; so i guess the service is/was not the problem. i include my crowsnest.conf file; with this config it works for me. 
To get the absolute path of the camera you could use `ls /dev/v4l/` like you would get the serial of the mcu. (someone mentioned to use the absolute path instead of the short one)

[crowsnest.txt](https://github.com/user-attachments/files/18518151/crowsnest.txt)
