### ISSUE TITLE
ArduCam 64MP issue

### ISSUE THREAD

**Issue by Maufeat** [ayufan/camera-streamer#31]
Hey first off thanks for the program. It has all needed features and is pretty neat.

I have compiled everything successful and placed the service into respecitve /service folder.

But it doesn't work, I have installed the official drivers, libcamera-apps and libcamera-dev. LibCamera works.

Now, when I try to start the server it runs but as soon as I want to access for example /snapshot I get a "Server Error". The respecitve service also doesn't run, I just get a timeout error when trying to enable it.

Here a screenshot, when trying to access /stream?res=low
![Bildschirmfoto 2023-01-17 um 18 47 41](https://user-images.githubusercontent.com/3602392/212973681-199fae48-d8e6-48a4-bdaa-664668f92b86.png)

**Comment by ayufan** [comment]
You need to copy script into service.
