### ISSUE TITLE
No signal... Address already in use

### ISSUE THREAD

**Issue by perrada69** [ayufan/camera-streamer#38]
Hi, I can't get the ArduCam MPx streaming to work.

I found this error in the logs:

```
Feb 06 19:01:10 mainsailos camera-streamer[8373]: bind: Address already in use
Feb 06 19:01:10 mainsailos systemd[1]: camera-streamer-arducam-16MP.service: Main process exited, code=exited, status=255/EXCEPTION
```

I searched the dark corners of the internet but couldn't find anything...

I use: MainsailOs, 32b

**Comment by ayufan** [comment]
The problem is that something is already running on a port 8080. Change port to something different with `--http-port 8081` or alike.
