### ISSUE TITLE
`--camera-{v,h}flip` throw an error now when they used to work with the same camera

### ISSUE THREAD

**Issue by foosel** [ayufan/camera-streamer#51]
Hey there, as already mentioned in [this comment on the OctoPrint project](https://github.com/OctoPrint/OctoPi-UpToDate/issues/2#issuecomment-1472597977) I'm seeing a regression with the current code with regards to flipping.

I just built a new binary of `v0.1-16-gcdb62ef (cdb62ef)` (current `master`) against the current RPi libcamera0 package, 0.0.4 (debian packaged version: 0~git20230302+923f5d70-1): https://github.com/OctoPrint/camera-streamer-archive/releases/tag/0.1-16-gcdb62ef-1

This runs great on my test image with RPiCam v3 and USB Camera, however I can no longer use `--camera-{v,h}flip` with the RPiCam like I could before (the USB camera says it doesn't support that in the first place). If I try, camera configuration fails:

```
octo@octopib:~ $ /usr/bin/camera-streamer --http-port=8080 --camera-type=libcamera --camera-path=/base/soc/i2c0mux/i2c@1/imx708@1a --camera-format=YUYV --camera-vflip=1 --camera-hflip=1
/usr/bin/camera-streamer Version: v0.1-16-gcdb62ef (cdb62ef)
[0:12:52.107127607] [1308]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[0:12:52.260933243] [1319]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media2 and ISP device /dev/media0
device/libcamera/device.cc: CAMERA: Device path=/base/soc/i2c0mux/i2c@1/imx708@1a opened
[0:12:52.261933303] [1308] ERROR Camera camera.cpp:1016 Can't configure camera with invalid configuration
device/libcamera/buffer_list.cc: CAMERA:capture: Failed to configure camera
```

I am absolutely sure this used to work with an earlier version, because back then I tested this and documented it on the OctoPrint community forums on February 22nd. The first user report of this no longer working reached me on March 6th with a (develop branch) build from February 28th. 

I've created an strace for you just in case this might help: [flip-strace.txt](https://github.com/ayufan/camera-streamer/files/11020913/flip-strace.txt). I'm happy to test anything or provide any further info you need.

From my understanding, based on the command output, this is failing inside libcamera, so either the interface changed, or there's a regression upstream?

**Comment by ayufan** [comment]
Hmm. I tried on my arm64 build with the same `libcamera0` version and it seems to work fine. I will check using Octoprint image, maybe the armhf behaves differently.

**Comment by ayufan** [comment]
Oh. It fails on armhf build.

**Comment by rlekey** [comment]
Any way to get this working with an old build?

**Comment by ayufan** [comment]
@rlekey It is not build specific. It is system-specific, or libcamera specific. Hard to say yet.

**Comment by foosel** [comment]
Am I understanding this correctly in that that would the  have the benefit of also working with any camera, regardless of hardware?

**Comment by ayufan** [comment]
Yes, that is the idea. It would require the client library to properly support this. Which is true for most part.

**Comment by mat100** [comment]
Unfortunately I have the same problem. I use your amazing camera streamer in Yocto kirkstone with the latest version of libcamera compiled from the raspberrypi repository. I'm using an ov5647 camera for which this setup has worked so far.

**Comment by foosel** [comment]
@ayufan Will look into this ASAP, might be a few days though. In any case, thank you so much for your work!

**Comment by rlekey** [comment]
@ayufan 

Looks like this is working on the develop branch, at least for a direct camera run using tools/libcamera_camera.sh --camera-vflip=1

It still does not seem to work with RESCALLER:STREAM options set in a url ("192.xxx.xxx.xxx/option?verticalflip=1")

I do get the confirmation that RESCALLER:STREAM: The 'verticalflip' was set to '1'. But it doesn't seem to effect the stream or video.

This no longer effects my use, as I can flip the pixels down the road, but figured you'd want to know about the bug. Thanks!

**Comment by ayufan** [comment]
> It still does not seem to work with RESCALLER:STREAM options set in a url
("192.xxx.xxx.xxx/option?verticalflip=1")

It will not work to change it dynamically.

**Comment by ayufan** [comment]
Lets wait till I merge this. It should happen over weekend.

**Comment by foosel** [comment]
Roger that. Are you still also thinking about switching the implementation over to doing this in software instead as mentioned in https://github.com/ayufan/camera-streamer/issues/51#issuecomment-1507374426, for the sake of USB camera owners? Or is that now off the table again? No pressure, just curious!

**Comment by ayufan** [comment]
@foosel 

I tried, exif worked, but was unable to achieve the same for h264 using display sei. So, no, this is no-go until I figure out the display sei.

I will try to re-implement this via rescaller, but it will come with performance penalty for USB cams since JPEG will have to be decoded, rescalled and encoded instead of just pass through.

Additionally, Olof from Bondtech (when discussing with @meteyou) mentioned that the easier trick (and more reliable) might be just doing cropping and rotation via css on frontend...

**Comment by foosel** [comment]
Yeah, rotating via frontend is something I already offer in OctoPrint as well since hour 1, but when I announced a potential (and now pretty much decided on) switch to camera-streamer as default camera stack on future versions of the image, I immediately got the feedback that rotation/flipping options in the backend are very much needed for certain workflows (my guess is alternative frontends without rotation built in).

Hence my curiousity. Personally, I never have had to use rotation or flipping myself, I simply mount the camera in the right orientation to begin with, but who am I to judge how people are forced to set up their stuff 😅

Thanks for clarifying! 😊

**Comment by ayufan** [comment]
> Hence my curiousity. Personally, I never have had to use rotation or flipping myself, I simply mount the camera in the right orientation to begin with, but who am I to judge how people are forced to set up their stuff 😅

I guess, sometimes it is hard. Overall 90o rotation is hard on memory bandwidth, but the horizontal/vertical flip is OK. Unsure, maybe the solution is a mix: use EXIF for JPEG (snapshot, to provide zero-copy solution), but use rescaller method for H264 since we already have to decode JPEG there so the additional rescaling step can be basically free, unsure yet.

**Comment by ayufan** [comment]
@foosel I merged the `camera-vflip/hflip` fix into `master` along some other smaller bits.

The `develop` only contains `crop` function on top of it.

I will close it, but if you could re-test it I would be grateful.

**Comment by foosel** [comment]
@ayufan Just built a package from `master` and things are still looking good here, `--camera-{h,v}flip` are functional against an RPiCam3! 👍

**Comment by progSides** [comment]
Just in case anyone (or me in the future) needs to know how to flip or rotate the camera image horizontally, vertically or both on the new v3 camera module... add this ( --camera-hflip=1 --camera-vflip=1 ) to the end of the default file below.  Notice: this is not --camera-options, it is camera-hflip, etc but it is on the same line.

/boot/camera-streamer/libcamera.conf
```### Options for libcamera based cameras (PiCam, Arducam, ...)

# The port on which the webcam server for the camera should listen on. If you have only
# one camera, leave at 8080. If you have more, change to 8081, 8082, etc. The primary
# camera will be considered the one with 8080.
PORT=8080

# The resolution to request on the camera sensor. Defaults to 1280x720.
WIDTH=1920
HEIGHT=1080

# The height to use for the video stream. Defaults to 720.
VIDEO_HEIGHT=720

# The height to use for the snapshots. Defaults to 1080.
SNAPSHOT_HEIGHT=1080

# The framerate to set on the camera. Defaults to 15fps.
FRAMERATE=15

# Additional options. By default enables continuous auto focus (if possible).
OPTIONS='--camera-options="AfMode=2" --camera-options="AfRange=2" --camera-hflip=1 --camera-vflip=1'```

**Comment by stuomas** [comment]
> Just in case anyone (or me in the future) needs to know how to flip or rotate the camera image horizontally, vertically or both on the new v3 camera module... add this ( --camera-hflip=1 --camera-vflip=1 ) to the end of the default file below. Notice: this is not --camera-options, it is camera-hflip, etc but it is on the same line.
> 
> /boot/camera-streamer/libcamera.conf
> 
> ```
> 
> # The port on which the webcam server for the camera should listen on. If you have only
> # one camera, leave at 8080. If you have more, change to 8081, 8082, etc. The primary
> # camera will be considered the one with 8080.
> PORT=8080
> 
> # The resolution to request on the camera sensor. Defaults to 1280x720.
> WIDTH=1920
> HEIGHT=1080
> 
> # The height to use for the video stream. Defaults to 720.
> VIDEO_HEIGHT=720
> 
> # The height to use for the snapshots. Defaults to 1080.
> SNAPSHOT_HEIGHT=1080
> 
> # The framerate to set on the camera. Defaults to 15fps.
> FRAMERATE=15
> 
> # Additional options. By default enables continuous auto focus (if possible).
> OPTIONS='--camera-options="AfMode=2" --camera-options="AfRange=2" --camera-hflip=1 --camera-vflip=1'
> ```

Hi, such file does not exist by default, should it be created? Where is this file documented?
