### ISSUE TITLE
No camera-specific scripts in tools folder

### ISSUE THREAD

**Issue by ExaurovNM** [ayufan/camera-streamer#64]
The documentation says that there should be camera-specific scripts for "High-performance mode via ISP for CSI"
but I can't find them.
This is the list of files in the tools folder:
```
csi_camera.sh  
dump_cameras.sh  
libcamera_camera.sh  
rpi_measure.sh  
rpi_mem_usage.sh  
run_all.bash  
usb_camera.sh
```

What I'm missing?

**Comment by ExaurovNM** [comment]
![image](https://github.com/ayufan/camera-streamer/assets/1872561/5196d4f2-ccc9-462a-adda-431c3cbecbec)
Im looking for "tools/imx519_camera.sh" for example. Can't see them here.

**Comment by ayufan** [comment]
Old, and gone. I think `csi_camera.sh` and `libcamera_camera.sh` are closest.
